# Generated by Django 2.2.7 on 2020-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type_of_quiz',
            field=models.CharField(choices=[('CL', 'Clasic'), ('WR', 'Writting'), ('CD', 'Codding')], default='CL', max_length=2),
        ),
    ]
