# Generated by Django 2.2.7 on 2020-05-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200409_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='code_text',
            field=models.CharField(max_length=1000, verbose_name='Input'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct_text',
            field=models.CharField(max_length=255, verbose_name='Text Answer'),
        ),
        migrations.CreateModel(
            name='Not_Singup_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_logined', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
